# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 01:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventMap', '0002_auto_20170724_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('startDate',)},
        ),
        migrations.AlterField(
            model_name='event',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 24, 22, 54, 38, 185022)),
        ),
        migrations.AlterField(
            model_name='event',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 24, 21, 54, 38, 185022)),
        ),
    ]
