# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 01:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventMap', '0003_auto_20170724_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 24, 22, 54, 59, 589354)),
        ),
        migrations.AlterField(
            model_name='event',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 24, 21, 54, 59, 589354)),
        ),
    ]
