# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 17:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventMap', '0009_auto_20170726_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 27, 15, 37, 54, 816889)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 27, 13, 37, 54, 816889)),
        ),
    ]
